# This is a config for E2B sandbox template.
# You can use 'template_id' (bf66ba92-bbe0-4108-a487-4483ae085ef0) or 'template_name (nextjs-developer) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='nextjs-developer')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'nextjs-developer' })

template_id = "bf66ba92-bbe0-4108-a487-4483ae085ef0"
dockerfile = "e2b.Dockerfile"
template_name = "nextjs-developer"
start_cmd = "/compile_page.sh"
cpu_count = 2
memory_mb = 512
team_id = "c5a50183-d02b-4175-9693-4dd0013f92b8"
