import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { RoadmapProvider } from "@/context/roadmap-context"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

function Footer() {
  return (
    <footer className="w-full py-6 border-t mt-auto">
      <div className="container mx-auto px-4">
        <p className="text-center text-sm text-gray-600">
          💧
          <a href="https://github.com/ondrejromancov/e2b-hackathon" className="hover:underline">
            Team MDR
          </a>
          {" - "}
          <a href="https://lu.ma/b9ekgwqf?tk=uhOjBm" className="hover:underline">
            2025 E2B Prague Hackathon
          </a>
        </p>
      </div>
    </footer>
  )
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <RoadmapProvider>
          <main className="flex-grow">{children}</main>
          <Footer />
        </RoadmapProvider>
      </body>
    </html>
  )
}
